export const Users = [
  {
    id:1,
    profilePicture: "persons/ross.jpg",
    username: "Ross Geller",
  },
  {
    id:2,
    profilePicture: "persons/joey.jpg",
    username: "Joey Tribbiani",
  },
  {
    id:3,
    profilePicture: "persons/chandler.jpg",
    username: "Chandler Bing",
  },
  {
    id:4,
    profilePicture: "persons/monica.jpg",
    username: "Monica Geller",
  },
  {
    id:5,
    profilePicture: "persons/rachel.jpg",
    username: "Rachel Green",
  },
  {
    id:6,
    profilePicture: "persons/pheebs.jpg",
    username: "Phoebe Buffay",
  }
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "posts/img8.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "posts/img9.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "posts/img10.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "posts/img11.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "posts/img12.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "posts/img13.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "posts/img14.jpg",
    date: "2 days ago",
    userId: 4,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "posts/img19.jpg",
    date: "3 days ago",
    userId: 5,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "posts/img20.jpg",
    date: "5 days ago",
    userId: 2,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "posts/img21.jpg",
    date: "1 week ago",
    userId: 1,
    like: 104,
    comment: 12,
  },
];
